steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/app:$COMMIT_SHA']
- name: gcr.io/cloud-builders/docker
  args: ['run', '--network=host', '-v', '/workspace:/workspace', '-v', '/var/run/docker.sock:/var/run/docker.sock',
         '--entrypoint=/bin/bash', 'gcr.io/cloud-builders/docker', '/workspace/test.sh']
images:
- gcr.io/$PROJECT_ID/app:$COMMIT_SHA