#!/bin/bash

echo "Content-type: text/html";
echo ""
echo "<html>"
echo "<body>"
echo "<p>"
echo "This cloud native app is running in Kubernetes!"
echo "</p>"
echo "<p>"
echo "Our pod name is:"
echo $(hostname)
echo "</p>"

echo "<p>"
echo "My bash version is:"
echo $(bash --version)
echo "</p>"

echo "</body>"
echo "</html>"
